### ISSUE TITLE
Type complexity + `LuauTarjanChildLimit` causes `*error-type*` for resolved requires

### ISSUE THREAD

**Issue by ghost** [JohnnyMorganz/luau-lsp#112]
```lua
local module = require(script:FindFirstChild("module"))
```

```lua
local module = {}

function module.execute(player: Player) end -- Won't occur with `player: Instance`.

return module
```

While I can jump to the module from the `require` line, `module` gets typed to `*error-type*`. This does not occur with "Fflags Enable By Default" off. I don't think this occurred five days ago.

I haven't yet been able to replicate this in a new project.

**Comment by JohnnyMorganz** [comment]
Strange..., I can reproduce this in my project, but not in a new project as well.

**Comment by JohnnyMorganz** [comment]
Few things I can uncover from this:
- Setting FFlag `LuauTarjanChildLimit` to 0 fixes this.
- Because we are using the autocomplete typechecker, we are subject to the dynamic limits set on the autocomplete (so that it resolves in a reasonable amount of time). Alternatively, setting `LuauAutocompleteDynamicLimits` to False can fix this (probably also why "fflags enable by default" causes this)
- If you don't want to use the autocomplete typechecker to provide hover information, you can disable `luau-lsp.hover.strictDatamodelTypes`. The side effect of disabling this means the limits are no longer used, so this should resolve correctly
- The error depends on the complexity of the types and complexity of the project the module is present in

**Comment by JohnnyMorganz** [comment]
The issue also occurs for external packages, e.g. https://wally.run/package/vorlias/net

**Comment by JohnnyMorganz** [comment]
From discord: It seems the issue is tied to the size of the sourcemap.
It is most likely our "makeLazyInstanceType" is expensive

**Comment by JohnnyMorganz** [comment]
I've manually enforced a lower bound of 15,000 on LuauTarjanChildLimit to help alleviate some issues.

**Comment by JohnnyMorganz** [comment]
There have been many changes since this was created.
I haven't seen this be reported as an issue as of late, so going to close as resolved.
