### ISSUE TITLE
`game` does not contain its children

### ISSUE THREAD

**Issue by nezuo** [JohnnyMorganz/luau-lsp#15]
`print(game.ReplicatedStorage)` reports the error: `TypeError: Key 'ReplicatedStorage' not found in class 'DataModel'`

It's considered good practice to use `game:GetService()` instead but it can be confusing when this doesn't work.

**Comment by JohnnyMorganz** [comment]
In terms of technically being correct, we might want to add this - but should we though?
I'm wondering if we should enforce best practices instead (i.e., using `:GetService`)

**Comment by nezuo** [comment]
If we wanted to enforce best practices it would help if it gave an error message indicating that the user should use `GetService` and maybe the reasons why.

**Comment by JohnnyMorganz** [comment]
This should actually no longer error after https://github.com/JohnnyMorganz/luau-lsp/commit/48a0abd56d5600c65d416645fdaf9646f8b76720, but we won't provide any autocomplete support currently - not sure how much its worth it to do so, because I'm not sure where to easily find all the direct children of DataModel

**Comment by JohnnyMorganz** [comment]
Since statically there is no way to find direct DataModel children, I don't think there is much else we can do here.
This will no longer error which is the main issue. The loss of autocomplete is minor IMHO.

This could, however, be supported by #81, as Studio has full knowledge of DataModel children, and we will be able to understand this. So I will close this in favour of that issue.
