### ISSUE TITLE
Errors when loading non-Roblox workspace

### ISSUE THREAD

**Issue by mikejohnstn** [JohnnyMorganz/luau-lsp#45]
I see the following two errors when opening a workspace that is vanilla Luau:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/515035/174896528-eccd495f-c45f-4609-9d66-44b1fd6fd33c.png">

I have disabled both of the settings mentioned in the readme:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/515035/174896715-24568594-4d3b-41b6-81e0-ead9f750d40c.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/515035/174896667-237d1283-b21f-48fc-a424-a141265c9bb4.png">

Interestingly I see these errors when I double-click to open a file in the workspace, not when the workspace is first opened.

**Comment by JohnnyMorganz** [comment]
Question for the documentation file one. Do you reckon people would be interested in feeding in their own documentation files for their definition files? Example of how its structured: https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/roblox/api-docs/en-us.json

I'm hoping that one day Luau will make it easier for me to attach and find (doc) comments for relevant types (#5), so that this is not necessary

**Comment by mikejohnstn** [comment]
I'd find it useful to add documentation to definition files, especially when working with other people. And I agree supporting doc comments in Luau itself would be great.

But in my opinion this is less important than making all the basics work well. Even without documentation, it's really helpful just being able to reliably see a function signature + types in autocomplete.

I find autocomplete is working well for all types in definition files, but it isn't working reliably yet for my own types added in Luau files. I think this is a known issue based on recent Discord chat, but if not let me know and I'll post a new issue.
