### ISSUE TITLE
File alias autocomplete should overwrite the existing string 

### ISSUE THREAD

**Issue by lolmanurfunny** [JohnnyMorganz/luau-lsp#479]
When autocompleting a file alias in a require call, the result is appended to the existing string instead of overwriting it.

![Code_R8PDH44HCG](https://github.com/JohnnyMorganz/luau-lsp/assets/77128366/af6710d7-be0b-438f-ac99-64c764699869)

**Comment by JohnnyMorganz** [comment]
What is your alias map?

**Comment by lolmanurfunny** [comment]
```json
"luau-lsp.require.fileAliases": {
  "@types": "src/ReplicatedStorage/Shared/Types",
  "@packages/ReplicaService": "src/ReplicatedStorage/Packages/Madwork/ReplicaService",
  "@packages/ReplicaController": "src/ReplicatedStorage/Packages/Madwork/ReplicaController",
}
```

**Comment by JohnnyMorganz** [comment]
The problem here is that your file aliases contain `/` characters, which we don't handle correctly. I wouldn't really recommend those kind of aliases.

Luau also disallows the `/` character in their upcoming require-by-string aliases mechanism: https://github.com/luau-lang/rfcs/blob/master/docs/require-by-string-aliases.md, so I am going to close this as a won't fix as it will become prohibited later anyways when we migrate to luau's version
