### ISSUE TITLE
Modularizing platform-specific behavior

### ISSUE THREAD

**Issue by voidedWarranties** [JohnnyMorganz/luau-lsp#500]
I'm not sure if this is in-scope for this project, but I'm trying to maintain a fork of luau-lsp for [godot-luau-script](https://codeberg.org/ksk/godot-luau-script) and am having difficulty dealing with the intersection of the Roblox and Godot-specific features.

Due to the complexity of this project, I've determined that "hard" forking (i.e. removing all of the Roblox functionality as a starting point) is not sustainable to maintain and has caused odd bugs that don't occur upstream. "Soft" forking, on the other hand, involves deciding how my code should coexist with Roblox-specific code. I don't see a clean way to do this without touching the Roblox code.

Would it be possible to separate Roblox-specific code (attaching magic functions/tags, autocomplete, candidate sorting, tag handling, color provider, etc.) into an abstract class that fork maintainers can then derive and implement for their own purposes? Then, for example, extension users would switch between platforms using preferences? I would be willing to make the initial patch for this.

Also, would it be possible to accept these non-Roblox platform implementations upstream? I understand there is an additional maintenance burden for this.

**Comment by JohnnyMorganz** [comment]
This is definitely something I'm open to and happy to consider.

My intention right now with the Roblox-specific stuff is that it is configurable. Disabling the relevant settings (`luau-lsp.types.roblox` and `luau-lsp.sourcemap.enabled`) *should* be giving you a Vanilla Luau experience with no Roblox-related stuff leaking through - if it isn't then that's a bug. Of course, these settings are currently on by default because Roblox-related code is the primary consumer right now, but I've been thinking about making the out-of-the-box experience more vanilla, and explicitly opting in here.

> attaching magic functions/tags, autocomplete, candidate sorting, tag handling, color provider, etc.

These things in particular shouldn't be having any impact on non-Roblox code (although maybe color provider is leaking through). Are you seeing any issues right now?

The internal code is very messy, sorry about that. I can see how it makes it challenging to fork/build off of. Also open to cleaning it up / defining clear boundaries.

By the way, what kind of things do you need for Godot that would require a fork / specific implementation? Curious if definition files is sufficient or you need more direct logic handling. Depending on the complexity we could accept the code.

One of my long-term stretch goals is to support Luau plugins for the language server, so that users can customise the experience for their specific platform, without having to mess with C++ code. Depending on what kind of stuff you need, do you think your modifications could fit into here? We would need to define proper interfaces etc., but understanding what's required would be a useful start.

**Comment by voidedWarranties** [comment]
My concern was not so much with the functionality, which is indeed mostly unaffected by Roblox code, but the dissatisfying way my code is mixed with Roblox code on the same paths (hooking into current code without making merging with upstream complex requires keeping Roblox code present and executing even though it's not relevant). Also, if Godot ever introduces classes named the same as those currently present in `LuauExt`, it will cause issues, and tag names cannot be shared between implementations.

I have had definition files done for godot-luau-script for a while now, but with just definitions the QOL is not great. Here are some of the things that need access to Luau's C++ interface:

- Completion and signature help within comments (for annotations required to register classes), currently implemented [here](https://codeberg.org/ksk/gls-lsp/src/branch/main/src/GlsSupport.cpp)
- Magic functions for `Duplicate` and `IsA` (similar to `Clone` and `IsA` in Roblox)
- Color providers, but for Godot functions
- Integration with the Godot editor (for example, to provide completion for node paths) - this is not currently a priority

Because some of this functionality is quite complicated, I don't think it's easily solved without an equally complicated Luau interface, although I agree that having this kind of interface would be better.

Which direction would be better? Could the Luau interface, if it materializes, be implemented using the abstract class method I described above?

**Comment by voidedWarranties** [comment]
Alright, if it's okay then I can start working on the initial implementation of the class interface. An early draft hopefully shouldn't take too long.

P.S. For a first C++ project this is quite impressive. Nice work!

**Comment by JohnnyMorganz** [comment]
Sure, that would be great! But prior warning that it may take me some time to review, and most likely propose iterations

I think given that other people are now also looking and using the code, it is enough prompt for me to start cleaning it up 😄. I'll start looking at that alongside this

**Comment by voidedWarranties** [comment]
I've managed to do much of the initial implementation (with some details missing) but have run into an issue with initializing workspaces:

In order to instantiate the correct interface object, the workspace needs to know its configuration. But it seems that the workspace is `initialize`d (definitions files loaded) before the configuration is received. Is it possible to delay workspace initialization enough to receive the configuration first?

https://github.com/JohnnyMorganz/luau-lsp/blob/4b41d6f24a81c0f30ccdecc53a3e9a9c80553941/src/LanguageServer.cpp#L488-L503

https://github.com/JohnnyMorganz/luau-lsp/blob/4b41d6f24a81c0f30ccdecc53a3e9a9c80553941/src/LanguageServer.cpp#L446-L460

**Comment by JohnnyMorganz** [comment]
Nice!

From first thoughts I think it should be *mostly* OK. The main issues arise when diagnostics start computing before config is received - #484, but this change shouldn't make that a difference, since we are (meant to be) delaying diagnostics until configured.

Config typically comes pretty quickly, so losing out on "special" autocomplete etc for <1 second on start up isn't really a problem (users probably haven't even started doing anything yet by the time we are configured!)
