### ISSUE TITLE
Color picker palette canvas is not calculating the width initially 

### ISSUE THREAD

**Issue by Barocena** [JohnnyMorganz/luau-lsp#510]
Palette canvas is not the right size when you hover on it

https://github.com/JohnnyMorganz/luau-lsp/assets/34089907/c8e52fa9-0eed-49e9-8613-2dc8201664da

the first picker works fine, but the second one with the type info have the problem

**Comment by JohnnyMorganz** [comment]
I had a look at this - our calculations are correct, the weird values are coming from VSCode. I think this should be reported as a vscode bug. Anecdotally, it looks like its because the hover info at the bottom makes the color picker wider, and then VSCode isn't doing the right computations on the widget

**Comment by JohnnyMorganz** [comment]
Issue will be fixed in the next VSCode release :) https://github.com/microsoft/vscode/issues/201509#issuecomment-3061636062
