### ISSUE TITLE
Add support for the Zed editor

### ISSUE THREAD

**Issue by filiptibell** [JohnnyMorganz/luau-lsp#597]
It would be great if luau-lsp supported the [Zed](https://zed.dev) editor which just recently got extensions support.
I think we could have a similar setup to the [Biome](https://github.com/biomejs/biome-zed) LSP extension.

Some things to consider:

- Does luau have a tree-sitter grammar that is up to par? Zed only supports tree-sitter
- Zed does not seem to support custom LSP requests just yet (for `$/command`)
- Zed requires extensions to be their own full git repository, but editor support is already neatly organized in this one repo 😕

**Comment by Malakai0** [comment]
All of the tree-sitter implementations of Luau grammar have had issues from my experience. It's probable that if this was attempted, making tree-sitter grammar for Luau from scratch would be necessary. I've had to do heavy modification to existing grammars in order to get my neovim configuration working fine.

**Comment by lopi-py** [comment]
There is this one used in neovim: https://github.com/tree-sitter-grammars/tree-sitter-luau/
I have no problems using it in neovim. Zed is using the grammars from the same github org (tree-sitter-grammars)

**Comment by techs-sus** [comment]
Many things have changed since the last update on this, but Zed added an extension API (or updated it?) to allow for LSP support. Teapo has graciously created an extension which perfectly works on Zed which adds LSP support, and configuration support. This extension has already gotten merged into the extension registry, and it is being maintained (see https://github.com/zed-industries/extensions/pull/1058).

Extension (created by teapo): https://github.com/4teapo/zed-luau

**Comment by JohnnyMorganz** [comment]
Going to close this as completed now that https://github.com/4teapo/zed-luau exists. Thank you 4teapo!
