### ISSUE TITLE
Disable completion without disabling auto-imports?

### ISSUE THREAD

**Issue by ghost** [JohnnyMorganz/luau-lsp#681]

**Comment by JohnnyMorganz** [comment]
Do you mind explaining your usecase here?

**Comment by Pymon02** [comment]
I have Roblox LSP and Luau LSP active since I like Roblox LSP's autocompletion, but I like Luau LSP's typing. With both of them it duplicates the autocompletion. Is there a way to disable it for Luau LSP?

**Comment by lolmanurfunny** [comment]
> Is there a way to disable it for Luau LSP?

No, there's currently no way to disable completion in Luau LSP *without* also disabling auto-imports. This is because the setting responsible for auto-imports, `luau-lsp.completion.imports.enabled`, is under the `luau-lsp.completion` namespace rather than having it as its own independent setting like how [Roblox LSP's config](https://github.com/NightrainsRbx/RobloxLsp/blob/7e768d91a0c4a3655e655ee54944e8505cd31574/server/script/config.lua#L218) has it.

**Comment by JohnnyMorganz** [comment]
> This is because the setting responsible for auto-imports, luau-lsp.completion.imports.enabled, is under the luau-lsp.completion namespace rather than having it as its own independent setting like how Roblox LSP's config has it.

This is not the reason. It does not make a difference where the config is located, and can be doable either way. Auto import is a type of autocomplete. Making it separable requires changes to our underlying completion operation structure.

**Comment by lolmanurfunny** [comment]
> This is not the reason. It does not make a difference where the config is located, and can be doable either way.

I didn't intend to imply that it was. I was just trying to give a simple explanation, but I guess it was misleading.

**Comment by JohnnyMorganz** [comment]
Unfortunately I do not think we are going to implement this anytime soon, so going to close this issue.
