### ISSUE TITLE
Automatic import suggestions slow down Luau LSP

### ISSUE THREAD

**Issue by Dizyreal** [JohnnyMorganz/luau-lsp#749]
When this property is enabled, Luau LSP works slower than usual, and there appears delay before automatic suggestions are shown.
![image](https://github.com/user-attachments/assets/18cef49f-0782-4051-91a7-b46fae6e3aa7) 

Also when Import Ignore Globs are empty, Luau LSP works way faster (2x-3x) even with enabled auto import suggestions.

**Comment by JoelBrd** [comment]
Second this.

**Comment by Mewious** [comment]
bump

**Comment by ColRealPro** [comment]
bump

**Comment by kennethloeffler** [comment]
@Mewious @ColRealPro 

It's great that you're enthusiastic about getting this fixed, but repeated messages that only say variations of "bump" will not make the issue get resolved faster since issues are not prioritized based only on recent activity, and disrespect the time of the author and others who follow activity on this repository because they'll get notifications for these messages which don't add any useful information or insights.

It's better to add some information that might actually help the issue get resolved, for example:
* a workaround
* more details on how to reproduce the issue
* the particular circumstances in which you're seeing the issue

If you just want a status update, that's fine - but it's more appropriate for this to happen in e.g. [this project's Discord channel](https://discord.com/channels/385151591524597761/1031990829474131998) and avoid cluttering the issue with it.

**Comment by JohnnyMorganz** [comment]
Been looking into this one, indeed the main culprit seems to be the call to `WorkspaceFolder::isIgnoredFileForAutoImports`.

Suggest imports currently takes 15s on my example code base. 

If I remove that call, the request goes down to 1.2s, where suggest imports takes 387ms. Interestingly, the computation of the actual completion items takes ~500ms, but we we pay ~600ms just to return that result back to the language client (most likely all the cost to serialize it back to JSON, so we may need to look into the size of the result and performance of our JSON library afterwards).

The cost for isIgnoredFileForAutoImports either comes from the path manipulation or the glob matching, so it is worth profiling the 2 to see if we can optimise it better. If there doesn't seem to be any easy wins, we can probably also cache the result of the ignore check so it's a 1 time cost (when creating the sourcemap).
