### ISSUE TITLE
Support for Sublime Text

### ISSUE THREAD

**Issue by badcc** [JohnnyMorganz/luau-lsp#79]
In-repo support for Sublime Text, like the VS Code plugin, would be amazing! I think it would not be too difficult to add basic support. Thanks!

**Comment by JohnnyMorganz** [comment]
Duplicate of #50

I definitely want it though! I've never used sublime text so I plan to look into it one day when I'm free.

It would be great if anyone interested could potentially contribute a starting point to using it in sublime text. I'm happy to maintain it from there. Otherwise I will try to get to it some time.

**Comment by badcc** [comment]
Sounds good thanks!
