### ISSUE TITLE
Types a and Player cannot be compared because they do not have the same metatable

### ISSUE THREAD

**Issue by Qualadore** [JohnnyMorganz/luau-lsp#83]
No warnings occur in Studio.
```lua
--!strict
local event = game:GetService("ReplicatedStorage"):FindFirstChild("RemoteEvent")
assert(event:IsA("RemoteEvent"), "") -- LSP does now recognize `event` as a `RemoteEvent`.

-- Won't warn if `player` is typed explicitly, but `Player` type is inferred anyway.
event.OnServerEvent:Connect(function(player, target: Player)
	print(player == target) -- Warning.
end)

local working_event: RemoteEvent = game:GetService("ReplicatedStorage"):FindFirstChild("RemoteEvent")
working_event.OnServerEvent:Connect(function(player, target: Player)
	print(player == target) -- No warning.
end)
```
```
TypeError: Types a and Player cannot be compared with == because they do not have the same metatable
```

**Comment by JohnnyMorganz** [comment]
This is because the typechecker actually resolves `event` as `any`, although the hover/autocomplete resolves it to a stricter type.
So typechecker doesn't actually recognise event as a RemoteEvent, so cannot infer `player` is Player.

Its a bit strange that the generic type cannot be compared. We could make the warning disappear by removing the metatable from Player, but it currently causes issues as we it no longer type checks against comparing with other types of no metatable (string/number etc.)

**Comment by Qualadore** [comment]
That's interesting, I thought `event` would've been inferred as `Instance` based on #76 and hovering over it. When you mentioned the possibility of `Instance:FindFirstChild()` returning `Instance?`, would that possibly let `event` be inferred as `Instance?` instead of `any`?

If not, I'd personally much rather write `local event: Instance?` than a metatable change that makes everything less safe.

**Comment by JohnnyMorganz** [comment]
The type diagnostics system and the hovering/autocomplete systems are two separate Luau typecheckers. The latter has stricter types than the former.

Unfortunately, the type diagnostics system infers all DataModel indexes as `any`: game, workspace, game.ReplicatedStorage.Modules, or FFC/WFC variants will all be typed as any in the eyes of the type diagnostics system.

Currently, there is no solution to that yet. We have to type it as any because we give the data model instances special types providing context where they are in the hierarchy, i.e. including pointers to their Parent and Children. This then makes the condition `Part' == Part` false, where `Part'` is the special datamodel type, since `Part'` has extra properties representing its children. This difference causes spurious errors to be thrown, so is currently disabled in the diagnostics system.

You will find the same in Studio:
![image](https://user-images.githubusercontent.com/19635171/180509347-a2d0ff56-c67c-453b-b6c1-7b1cddee3ba7.png)
It just doesn't warn because of the metatable differences

**Comment by JohnnyMorganz** [comment]
Unlike in Studio, we use the autocomplete typechecker to power hover information, which is why Luau LSP's hover information is typically better than Studio, but it doesn't exactly represent what the diagnostic system sees

**Comment by Qualadore** [comment]
Knowing that I think this is expected behavior. Thanks!
