### ISSUE TITLE
When the sourcemap file is nested under a directory, it's evaluated from project root.

### ISSUE THREAD

**Issue by ffrostfall** [JohnnyMorganz/luau-lsp#863]
Example: When the sourcemap path is set to `build/sourcemap.json`, Luau LSP evaluates it from the project root instead of from `build/`.

**Comment by JohnnyMorganz** [comment]
For my understanding, how did you generate the file, and are the file paths in the file relative to the project root or the build/ directory?

**Comment by ffrostfall** [comment]
I generated the file by doing `rojo sourcemap build.project.json --output=build/sourcemap.json`

The file paths in the sourcemap are relative to the sourcemap file, not the project root.

**Comment by JohnnyMorganz** [comment]
I just checked this, and I could not reproduce what you are saying.

I ran `rojo sourcemap --output testing/sourcemap.json`, and the filePaths in the sourcemap are relative to the CWD where I exectuted rojo, not where the output sourcemap lives. This is with `Rojo 7.4.4`.

**Comment by ffrostfall** [comment]
> I just checked this, and I could not reproduce what you are saying.
> 
> I ran `rojo sourcemap --output testing/sourcemap.json`, and the filePaths in the sourcemap are relative to the CWD where I exectuted rojo, not where the output sourcemap lives. This is with `Rojo 7.4.4`.

I'm sorry, I miscommunicated.

The sourcemap paths are relative to the CWD, yes. However, Luau LSP will evaluate the sourcemap from the *project root*. If the cwd is not the project root, this causes issues.

The desired behavior is for Luau LSP to evaluate sourcemap paths from the location of the sourcemap.

**Comment by JohnnyMorganz** [comment]
But the location of the sourcemap is not necessarily the CWD?

There is nothing tying back the CWD when executing the command and the actual sourcemap, so it is difficult to resolve this. If I run the command you initially gave, `rojo sourcemap build.project.json --output=build/sourcemap.json` in cwd "X", it would still be broken - the paths would be relative to "X", but the sourcemap lives in "X/build".

For now, I think this is working as intended, since the Luau LSP extension by default will set the CWD to the project root, and we allow `luau-lsp.sourcemap.sourcemapFile` to be configurable. I'd be open to changing this if Rojo starts making the paths in the sourcemap relative to the sourcemap file (which I think is a better approach)
