### ISSUE TITLE
Does not work properly with "Loader" library.

### ISSUE THREAD

**Issue by efreeti** [JohnnyMorganz/luau-lsp#883]
I'm using Nevermore Engine and Rojo to build my code. Currently this stack uses "Loader" library to load modules - https://mullets-gavin.github.io/Loader/loader.html

Current version of this extension is not working well with it showing: `TypeError: Unknown require: game/ServerScriptService/...[1011](https://luau-lang.org/typecheck)` for the following code `local require = require(script.Parent.loader).load(script)`

<img width="1085" alt="Lua error" src="https://github.com/user-attachments/assets/be4859ef-805a-4062-bdd5-f2b153dcba7a" />

**Comment by JohnnyMorganz** [comment]
Unfortunately it is unlikely for the server to support custom require loaders any time soon. The usage of global require is hardcoded in the Luau type system at the moment, so that would have to be extracted. Luau has no way to dynamically resolve requires.

There is an open issue https://github.com/JohnnyMorganz/luau-lsp/issues/595 about creating "plugins" similar to Roblox LSP so that one could do equivalent to `--@module` annotation, but that will also not be coming anytime soon.

For now, there are a couple options:
1) Type your requires as any `(require(script.Parent.loader) :: any)`. But you will lose all intellisense and autocomplete for this.
2) Force type cast your requires with a type assertion `require("...") :: typeof(require(game.ServerScriptService.My.Static.Path))`
3) Type the loader module require with a static overload, something like `((path: "Library") -> typeof(require(path.to.Library))) & ((path: "Utils") -> typeof(require(path.to.Utils))) & ...`
